<a href="https://colab.research.google.com/github/cabreonictor/Ciencia-de-Datos-y-Optimizacion-de-Modelos/blob/main/notebook/Proyecto_Ciencia_de_Datos_y_Optimizaci%C3%B3n_de_Modelos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Proyecto Integrador Ciencia de Datos

## Análisis exploratorio de datos sobre obesidad y factores de riesgo

**Integrantes:** Nancy Ferro - Angeles Deluca - Jimena Lasci - Lucio Mamani

# 1. Objetivo y alcances

El objetivo del presente trabajo es analizar un conjunto de datos relacionado con la salud y hábitos de la población, con el fin de identificar factores que influyen en el índice de masa corporal (IMC) y la presencia de obesidad.

Se busca comprender la relación entre variables como edad, sexo, actividad física y condiciones de salud (diabetes, hipertensión, entre otras) con la clasificación del IMC.

Este análisis permitirá obtener información relevante para la toma de decisiones y la posterior construcción de modelos predictivos.

# 2. Análisis exploratorio de datos

## Preguntas guía para la exploración
1. ¿Cuáles serían mis variables de entrada y cuáles las de salida?  
2. ¿Es posible caracterizar la obesidad sólo mediante el índice de masa corporal, o se podría incluir más variables, como la medida de la cintura o alguna otra?  
3. ¿Hay alguna variable en el dataset que determine la proporción de grasa en el cuerpo?  
4. ¿Existen diferencias apreciables en la obesidad según características generales como la edad, el género o el nivel socioeconómico?  
5. ¿Se cumplen los supestos generalmente conocidos respecto a la actividad física, el sedentarismo, la calidad de la alimentación y la obesidad?  
6. ¿Está la obesidad fuertemenete relacionada con otras enfermedades?

In [2]:
# CARGA DEL DATASET:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

URL = ('https://github.com/cabreonictor/Ciencia-de-Datos-y-Optimizacion-de-Modelos/raw/refs/heads/main/data/base%20para%20publicar%20obesidad%20C%C3%B3rdoba.xls')
df = pd.read_excel(URL)
df.head()

,n_encuesta,dia,mes,est,ecar,hta,HTA,dlp,ec,ic,...,Fef,Fer,Naf,Nar,Kf,Kr,acúrf,acúrr,Ncomr,id
0,1,6,11,4,2,2,2,1,1,1,...,12.37,7.58,1124.74,689.40,1908.62,1902.34,431.19,875.75,4.0,1
1,2,6,11,4,1,1,1,1,2,1,...,9.50,10.20,1576.12,928.59,1896.30,1834.77,530.22,753.23,5.0,2
2,3,6,11,4,2,1,1,1,1,1,...,9.62,10.38,1199.42,909.87,2310.79,2321.60,481.01,935.28,4.0,3
3,4,6,11,4,1,1,1,1,1,1,...,4.81,0.00,661.66,0.00,1829.69,0.00,295.65,0.00,0.0,4
4,5,7,11,4,1,1,1,1,1,1,...,10.09,0.00,1001.07,0.00,2061.93,0.00,539.30,0.00,0.0,5

## Variables relevantes

Variables relevantes:

**Características físicas:**  
peso: var. cuantitativa en [kg]  
talla: var. cuantitativa en [m]  
imc: (índice de masa corporal) var. cuantitativa en [kg/m^2]  
clasifIMC: (grado de obesidad) var. cualitativa  
cc: (circunferencia de cintura) var. cuantitativa en [cm]
  
**Alimentación:**  
Gcarhue: (carnes y huevos) var. cuantitativa en [gr/día]    
Ghort: (hortalizas) var. cuantitativa en [gr/día]  
Gcetu: (cereales y tubérculos) var. cuantitativa en [gr/día]  
Gceint: (cereales integrales) var. cuantitativa en [gr/día]  
Gazmil: (azúcar y miel) var. cuantitativa en [gr/día]  
  
**Hábitos:**  
fuma: var. cualitativa 1- no; 2- si  
actfis: (actividad física) var. cualitativa 1- no; 2- si  
durac: (duración de la actividad física) var. cuantitativa en [min]  
veces: (cantidad de veces por semana que realiza la actividad) var. cuantitativa  
senth: (tiempo que pasa el individuo sentado) var. cuantitativa en [hr]  

**Datos personales:**  
sexo: var. cualitativa 1-sexo masculino. 2- sexo femenino  
edad: var. cuantitativa en [años]  
eciv: (estado civil) var. cualitativa  
nhijos: (número de hijos) var. cuantitativa (sin hijos = 999)  

**Enfermedades:**  
ecar: (Presencia de enfermedad cardiovascular) var. cualitativa 1- no; 2- si.  
hta: (Presencia de hipertensión arterial) var. cualitativa 1- no; 2- si  
dlp: (Presencia de dislipemia) var. cualitativa 1- no; 2- si  
ec: (Presencia de enfermedad cardíaca) var. cualitativa 1- no; 2- si  
ic: (Presencia de insuficiencia cardíaca) var. cualitativa 1- no; 2- si  
ten1max: (máxima de tensión arterial) var. cuantitativa [mm Hg]  
ten1min: (mínima de tensión arterial) var. cuantitativa [mm Hg]  
dbt: (Presencia de diabetes) var. cualitativa 1- no; 2- si  
cancer: 1- no; 2- si.  

**Nivel socioeconómico:**  
eent: (educación del entrevistado) var. cualitativa   
nes: (nivel económico social) var. cualitativa   

El dataset posee además variables referidas al consumo de alimentos específicos.

## Análisis descriptivo
### Medidas de tendencia central, medidas de dispersión y correlaciones

In [4]:
# INFO DEL DATASET:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4292 entries, 0 to 4291
Columns: 239 entries, n_encuesta to id
dtypes: float64(186), int64(45), object(8)
memory usage: 7.8+ MB

In [5]:
# MEDIDAS DE TENDENCIA CENTRAL Y DE DISPERSIÓN:

df.describe()

,n_encuesta,dia,mes,est,ecar,hta,HTA,dlp,ec,ic,...,Fef,Fer,Naf,Nar,Kf,Kr,acúrf,acúrr,Ncomr,id
count,4292.000000,4292.000000,4292.000000,4292.000000,4292.000000,4292.000000,4292.000000,4292.000000,4292.000000,4292.000000,...,4292.000000,4292.000000,4.167000e+03,4292.000000,4273.000000,4292.000000,4273.000000,4292.000000,4254.000000,4292.000000
mean,2158.263979,3.493476,8.753495,3.050326,1.265377,1.188490,1.321761,1.092731,1.020736,1.016775,...,16.211445,3.160669,2.201504e+03,370.232789,3221.463014,515.903781,1420.732976,231.076130,0.830042,2146.500000
std,1241.728159,1.809039,3.122049,1.080012,0.441585,0.391149,0.467206,0.290088,0.142517,0.128444,...,46.253986,51.904748,2.286985e+04,998.655104,7795.825878,3468.338785,2328.264453,534.349807,1.718225,1239.138007
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,1086.750000,2.000000,7.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,9.860000,0.000000,1.143050e+03,0.000000,2113.240000,0.000000,833.380000,0.000000,0.000000,1073.750000
50%,2159.500000,3.000000,9.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,12.920000,0.000000,1.704820e+03,0.000000,2825.260000,0.000000,1236.780000,0.000000,0.000000,2146.500000
75%,3233.250000,5.000000,11.000000,4.000000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,...,16.832500,0.000000,2.415035e+03,0.000000,3721.720000,0.000000,1744.040000,0.000000,0.000000,3219.250000
max,4306.000000,7.000000,12.000000,4.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,1756.000000,3344.850000,1.473039e+06,14776.300000,362610.000000,209075.000000,104467.000000,7401.780000,7.000000,4292.000000

In [7]:
# CORRELACIONES (PEARSON):

df.corr(numeric_only=True)

,n_encuesta,dia,mes,est,ecar,hta,HTA,dlp,ec,ic,...,Fef,Fer,Naf,Nar,Kf,Kr,acúrf,acúrr,Ncomr,id
n_encuesta,1.000000,-0.040417,-0.334972,-0.137284,-0.026869,-0.031114,0.050371,-0.009679,-0.030932,-0.047528,...,0.024053,-0.013606,0.026534,0.085966,0.011153,-0.005753,-0.010345,-0.000409,-0.003709,0.999997
dia,-0.040417,1.000000,0.039905,0.040007,0.004064,0.013430,0.029644,-0.007285,-0.026141,-0.012567,...,-0.003524,-0.023631,0.012477,-0.034947,-0.000655,0.009504,0.023151,-0.013902,-0.009982,-0.040299
mes,-0.334972,0.039905,1.000000,0.600213,-0.013224,-0.014041,0.011731,-0.024417,-0.013650,0.027749,...,0.033209,0.016326,0.009829,-0.005708,-0.002924,0.015194,-0.069175,0.032376,0.032225,-0.334643
est,-0.137284,0.040007,0.600213,1.000000,-0.008464,-0.005910,0.033484,0.029732,-0.009810,0.027512,...,-0.079265,0.019930,-0.034559,0.023033,0.010734,0.028146,-0.060747,0.064248,0.089675,-0.136562
ecar,-0.026869,0.004064,-0.013224,-0.008464,1.000000,0.800509,0.595870,0.020703,-0.039321,0.020104,...,-0.002329,0.021265,-0.014909,-0.045739,0.027816,-0.017015,0.046004,-0.013257,-0.019753,-0.026970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kr,-0.005753,0.009504,0.015194,0.028146,-0.017015,-0.013522,-0.010302,-0.002627,-0.006274,-0.003753,...,-0.006875,0.046686,0.008930,0.197621,-0.003952,1.000000,-0.004808,0.270503,0.270739,-0.005814
acúrf,-0.010345,0.023151,-0.069175,-0.060747,0.046004,0.049846,0.048565,-0.004465,-0.007282,0.000182,...,0.021356,-0.001238,-0.003594,0.002926,0.015662,-0.004808,1.000000,0.037846,0.005044,-0.010505
acúrr,-0.000409,-0.013902,0.032376,0.064248,-0.013257,-0.016439,0.010699,0.009323,-0.023233,0.000955,...,-0.022127,0.126269,0.006507,0.540790,-0.010283,0.270503,0.037846,1.000000,0.759758,-0.000535
Ncomr,-0.003709,-0.009982,0.032225,0.089675,-0.019753,-0.018502,-0.002439,0.020506,-0.006571,0.004494,...,-0.023712,0.109547,-0.008613,0.572889,-0.009615,0.270739,0.005044,0.759758,1.000000,-0.003719
id,0.999997,-0.040299,-0.334643,-0.136562,-0.026970,-0.031185,0.050420,-0.009741,-0.030945,-0.047542,...,0.024018,-0.013663,0.026538,0.085895,0.011151,-0.005814,-0.010505,-0.000535,-0.003719,1.000000